# Generated by Django 2.2.24 on 2021-12-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tel',
        ),
    ]
