# Generated by Django 2.2.24 on 2021-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_booking_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
    ]
